site_name: Ultimate Starter Kit
site_url: https://hfjooste.github.io/UltimateStarterKit
repo_url: https://github.com/hfjooste/UltimateStarterKit
repo_name: hfjooste/UltimateStarterKit
remote_branch: docs
remote_name: git@github.com:hfjooste/UltimateStarterKit.git
extra_css: [styles.css]
plugins:
  - with-pdf:
      author: Henry Jooste
      cover: true
      cover_title: Ultimate Starter Kit
      cover_subtitle: Documentation
extra:
  social:
    - name: Sponsor Development
      icon: fontawesome/solid/heart
      link: https://github.com/sponsors/hfjooste
    - name: Linktree
      icon: fontawesome/solid/link
      link: https://linktr.ee/hfjooste
    - name: Mastodon
      icon: fontawesome/brands/mastodon
      link: https://mastodon.gamedev.place/@hfjooste
    - name: Reddit
      icon: fontawesome/brands/reddit
      link: https://www.reddit.com/user/HenryJooste
    - name: Twitter
      icon: fontawesome/brands/twitter 
      link: https://twitter.com/hfjooste
    - name: GitHub
      icon: fontawesome/brands/github
      link: https://github.com/hfjooste
    - name: Email
      icon: fontawesome/solid/envelope
      link: mailto:henryjooste95@gmail.com
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: pink
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
nav:
  - Getting Started: index.md
  - Support the Project: support.md
  - Special Thanks: specialthanks.md
  - Core Functionality:
    - Input Devices: inputdevice.md
    - Game Instance: gameinstance.md
  - Logger: logger.md
  - Trackable Data:
    - Overview: trackabledataoverview.md
    - Data: trackabledata.md
    - Component: trackabledatacomponent.md
  - Audio:
    - Audio Overview: audio.md
    - Audio Utils: audioutils.md
    - Music Player: music.md
  - 3D Platformer:
    - Overview: platformer.md
    - Character: platformercharacter.md
    - Animation Instance: platformeranimation.md
    - Shadow Decal: platformershadow.md
  - Items:
    - Allowed Collector: allowedcollector.md
    - Collectable Item: collectableitem.md
  - UI & Widgets:
    - Collectable Item Icon: collectableitemicon.md
    - Credits:
      - Credits Entry: creditsentry.md
      - Credits Widget: creditswidget.md
    - FPS Counter: fpscounter.md
    - Input Indicator: inputindicator.md
    - Input Indicator Icon: inputindicatoricon.md
    - Menu: menu.md
    - Menu Item:
      - Navigation: menunavigation.md
      - Value Update Method: menuitemvalueupdatemethod.md
      - Menu Item Widget: menuitem.md
  - Utils:
    - Config Utils: configutils.md
    - Platform:
      - Platform Type: platformtype.md
      - Platform Utils: platformutils.md
    - Project Utils: projectutils.md