site_name: Ultimate Starter Kit
site_url: https://hfjooste.github.io/UltimateStarterKit
repo_url: https://github.com/hfjooste/UltimateStarterKit
repo_name: hfjooste/UltimateStarterKit
remote_branch: docs
remote_name: git@github.com:hfjooste/UltimateStarterKit.git
extra_css: [styles.css]
plugins:
  - with-pdf:
      author: Henry Jooste
      cover: true
      cover_title: Ultimate Starter Kit
      cover_subtitle: Documentation
extra:
  social:
    - name: Mastodon
      icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@hfjooste
    - name: Twitter
      icon: fontawesome/brands/twitter 
      link: https://twitter.com/HenryJoosteDev
    - name: GitHub
      icon: fontawesome/brands/github
      link: https://github.com/hfjooste
    - name: Email
      icon: fontawesome/solid/envelope
      link: mailto:henryjooste95@gmail.com
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: pink
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
nav:
  - Getting Started: index.md
  - Core Functionality:
    - Input Devices: inputdevice.md
    - Game Instance: gameinstance.md
  - Logger: logger.md
  - Trackable Data:
    - Overview: trackabledataoverview.md
    - Data: trackabledata.md
    - Component: trackabledatacomponent.md
  - Audio:
    - Audio Overview: audio.md
    - Audio Utils: audioutils.md
    - Music Player: music.md
  - 3D Platformer:
    - Overview: platformer.md
    - Character: platformercharacter.md
    - Animation Instance: platformeranimation.md
    - Shadow Decal: platformershadow.md
  - UI & Widgets:
    - Input Indicator: inputindicator.md
    - Input Indicator Icon: inputindicatoricon.md